# Generated by Django 3.2.25 on 2026-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251226_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.TextField(blank=True, null=True, verbose_name='人脸特征编码'),
        ),
    ]
