# Generated by Django 3.2.25 on 2026-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='折扣率'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_level',
            field=models.SmallIntegerField(choices=[(0, '普通会员'), (1, '银卡会员'), (2, '金卡会员'), (3, '钻石会员')], default=0, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_consume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计消费'),
        ),
    ]
