# Generated by Django 3.2.25 on 2026-04-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supl_name', models.CharField(help_text='供应商的名称', max_length=100, verbose_name='供应商名称')),
                ('supl_addr', models.CharField(blank=True, help_text='供应商的地址', max_length=200, verbose_name='供应商地址')),
                ('supl_phone', models.CharField(blank=True, help_text='供应商的联系电话', max_length=20, verbose_name='供应商联系电话')),
                ('wechat', models.CharField(blank=True, help_text='供应商的微信号', max_length=50, verbose_name='供应商微信')),
                ('business_license', models.CharField(blank=True, help_text='供应商的营业执照号', max_length=100, verbose_name='供应商营业执照')),
                ('level', models.CharField(blank=True, help_text='供应商的等级', max_length=20, verbose_name='供应商等级')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'tb_supplier',
            },
        ),
    ]
