# Generated by Django 3.2.25 on 2026-05-01 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_spec', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('purchase_num', models.IntegerField(verbose_name='进货数量')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('purchase_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进货时间')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商进货记录',
                'verbose_name_plural': '供应商进货记录',
                'ordering': ['-purchase_time'],
            },
        ),
    ]
