# Generated by Django 3.2.25 on 2026-05-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplierpurchaserecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplierpurchaserecord',
            table='tb_supplier_purchase',
        ),
    ]
