# Generated by Django 3.2.25 on 2026-05-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_purchase_db_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, help_text='供应商Logo/展示图片', null=True, upload_to='suppliers/', verbose_name='供应商图片'),
        ),
        migrations.CreateModel(
            name='SupplierImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='supplier/licenses/', verbose_name='营业执照/资质图片')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商营业执照',
                'verbose_name_plural': '供应商营业执照',
                'db_table': 'tb_supplier_image',
            },
        ),
    ]
