# Generated by Django 3.2.25 on 2026-05-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20260503_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='image',
            new_name='default_image',
        ),
    ]
