# Generated by Django 3.2.25 on 2026-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_rename_image_supplier_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='default_image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='suppliers/licenses/', verbose_name='营业执照'),
        ),
    ]
