# Generated by Django 3.2.25 on 2026-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpurchaserecord',
            name='barcode',
            field=models.CharField(blank=True, help_text='商品的条形码', max_length=50, verbose_name='商品条码'),
        ),
        migrations.AddField(
            model_name='supplierpurchaserecord',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='商品的过期日期', null=True, verbose_name='过期日期'),
        ),
        migrations.AddField(
            model_name='supplierpurchaserecord',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='supplierpurchaserecord',
            name='shelf_life',
            field=models.IntegerField(default=0, help_text='保质期，单位为天', verbose_name='保质期(天)'),
        ),
    ]
