# Generated by Django 3.2.25 on 2026-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_auto_20260813_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpurchaserecord',
            name='damaged_num',
            field=models.IntegerField(default=0, help_text='破损商品数量', verbose_name='破损数量'),
        ),
        migrations.AddField(
            model_name='supplierpurchaserecord',
            name='near_expiry_num',
            field=models.IntegerField(default=0, help_text='临保质期商品数量', verbose_name='临保质期数量'),
        ),
        migrations.AddField(
            model_name='supplierpurchaserecord',
            name='qualified_num',
            field=models.IntegerField(default=0, help_text='合格商品数量', verbose_name='合格数量'),
        ),
    ]
