# Generated by Django 3.2.16 on 2026-04-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20251226_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='sku',
            name='shelf_life',
            field=models.IntegerField(default=0, verbose_name='保质期(天)', help_text='请输入保质期，单位为天'),
        ),
    ]
