# Generated by Django 3.2.25 on 2026-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20260415_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='default_image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='goods/', verbose_name='默认图片'),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='image',
            field=models.ImageField(upload_to='goods/', verbose_name='图片'),
        ),
    ]
