# Generated by Django 3.2.25 on 2026-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20260424_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='商品的过期日期', null=True, verbose_name='过期日期'),
        ),
    ]
