# Generated by Django 3.2.25 on 2026-07-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20260503_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='brand/', verbose_name='默认Logo图片'),
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='brand/', verbose_name='图片')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌图片',
                'verbose_name_plural': '品牌图片',
                'db_table': 'tb_brand_image',
            },
        ),
    ]
