# Generated by Django 3.2.25 on 2026-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20260707_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo图片'),
        ),
        migrations.DeleteModel(
            name='BrandImage',
        ),
    ]
