# Generated by Django 3.2.25 on 2026-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20260727_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='expired_num',
            field=models.IntegerField(default=0, help_text='过期商品数量', verbose_name='过期商品数量'),
        ),
        migrations.AddField(
            model_name='sku',
            name='near_expiry_num',
            field=models.IntegerField(default=0, help_text='临保质期商品数量', verbose_name='临保质期数量'),
        ),
    ]
