# Generated by Django 3.2.25 on 2026-08-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20260813_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spu',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat2_spu', to='goods.goodscategory', verbose_name='二级类别'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat3_spu', to='goods.goodscategory', verbose_name='三级类别'),
        ),
    ]
