# Generated by Django 3.2.25 on 2026-07-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20251226_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='content/', verbose_name='默认图片'),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='content/', verbose_name='图片')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content', verbose_name='广告内容')),
            ],
            options={
                'verbose_name': '广告内容图片',
                'verbose_name_plural': '广告内容图片',
                'db_table': 'tb_content_image',
            },
        ),
    ]
