# Generated by Django 3.2.25 on 2026-05-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordergoods_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '货到付款'), (2, '支付宝'), (3, '微信支付')], default=1, verbose_name='支付方式'),
        ),
    ]
