# Generated by Django 3.2.25 on 2026-06-18 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0007_auto_20260503_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备ID')),
                ('port', models.CharField(max_length=50, verbose_name='串口端口')),
                ('baud_rate', models.IntegerField(default=9600, verbose_name='波特率')),
                ('status', models.SmallIntegerField(choices=[(1, '在线'), (2, '离线'), (3, '故障')], default=2, verbose_name='设备状态')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
            ],
            options={
                'verbose_name': '条码扫描器',
                'verbose_name_plural': '条码扫描器',
                'db_table': 'tb_barcode_scanner',
            },
        ),
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='找零')),
                ('payment_method', models.SmallIntegerField(choices=[(1, '现金'), (2, '支付宝'), (3, '微信支付'), (4, '银行卡')], default=1, verbose_name='支付方式')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已取消')], default=1, verbose_name='订单状态')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='收银员')),
            ],
            options={
                'verbose_name': '收银台订单',
                'verbose_name_plural': '收银台订单',
                'db_table': 'tb_pos_order',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='POSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posorder', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.sku', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '收银台订单商品',
                'verbose_name_plural': '收银台订单商品',
                'db_table': 'tb_pos_order_item',
            },
        ),
    ]
