# Generated by Django 3.2.25 on 2026-06-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='商品总数'),
        ),
    ]
