# Generated by Django 3.2.25 on 2026-07-25 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_posorder_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_count', models.IntegerField(default=0, verbose_name='商品总数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('cart_data', models.TextField(verbose_name='购物车数据JSON')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='收银员')),
            ],
            options={
                'verbose_name': '挂单',
                'verbose_name_plural': '挂单',
                'db_table': 'tb_suspended_order',
                'ordering': ['-create_time'],
            },
        ),
    ]
