# Generated by Django 3.2.25 on 2026-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_suspendedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已取消'), (9, '已删除')], default=1, verbose_name='订单状态'),
        ),
    ]
