# Generated by Django 3.2.25 on 2026-08-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0004_alter_posorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_orders', to=settings.AUTH_USER_MODEL, verbose_name='会员'),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_orders', to=settings.AUTH_USER_MODEL, verbose_name='收银员'),
        ),
    ]
