# Generated by Django 3.2.25 on 2026-08-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20260727_1609'),
        ('pos', '0005_auto_20260810_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='discount_type',
            field=models.CharField(default='member', max_length=20, verbose_name='折扣类型'),
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('discount_type', models.SmallIntegerField(choices=[(1, '固定折扣率'), (2, '固定金额优惠')], default=1, verbose_name='折扣类型')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='折扣率')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('start_time', models.DateTimeField(verbose_name='促销开始时间')),
                ('end_time', models.DateTimeField(verbose_name='促销结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(default='', verbose_name='促销说明')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.sku', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '促销商品',
                'verbose_name_plural': '促销商品',
                'db_table': 'tb_promotion_product',
                'ordering': ['-create_time'],
            },
        ),
    ]
