# Generated by Django 3.2.25 on 2026-08-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20260810_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='原始总金额'),
        ),
    ]
