# Generated by Django 3.2.25 on 2026-08-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_posorder_original_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='折扣率'),
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='discount_type',
            field=models.CharField(default='none', max_length=20, verbose_name='折扣类型'),
        ),
    ]
