# Generated by Django 3.2.25 on 2026-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20260810_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='原始单价'),
        ),
    ]
