# Generated by Django 3.2.25 on 2026-08-11 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0009_posorderitem_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspendedorder',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_orders', to=settings.AUTH_USER_MODEL, verbose_name='会员'),
        ),
    ]
