"""
Django settings for hot_mall project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 追加导包路径，简化添加子应用名
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'kvi0v!ci@yx&h!2rcc3472%_y+k@ho7fiw4mo0xf52e*^va5iw'
SECRET_KEY = 'pk&k!oyoa!q56h!2!4ek5(vhxsq=su4xx%9ng^tt+j_^9+3sm4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'multiupload',
    'widget_tweaks',
    'users',
    'verifications',
    'areas',
    'haystack',
    'contents',
    'goods',
    'orders',
    'payment',
    'gms',
    'suppliers',
    'pos',
    'lottery',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'hot_mall.license_middleware.LicenseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 商业授权配置：公钥由部署环境注入，私钥只保存在许可方签发环境。
LOCAL_LICENSE_DIR = os.path.join('/tmp', 'hot_mall_dev_license')
LICENSE_FILE = os.getenv('LICENSE_FILE', os.path.join(LOCAL_LICENSE_DIR, 'license.json'))
LICENSE_PUBLIC_KEY = os.getenv('LICENSE_PUBLIC_KEY', '')
LICENSE_PUBLIC_KEY_FILE = os.getenv(
    'LICENSE_PUBLIC_KEY_FILE', os.path.join(LOCAL_LICENSE_DIR, 'public.pem')
)

ROOT_URLCONF = 'hot_mall.urls'

TEMPLATES = [
    # Django模板引擎 - 用于admin应用和app模板
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # 添加主模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    # Jinja2模板引擎配置信息 - 用于项目模板
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 模板文件加载路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 补充Jinja2模板引擎环境
            'environment': 'hot_mall.utils.jinja2_env.jinja2_environment',
        },
    },
]

WSGI_APPLICATION = 'hot_mall.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'HOST': '127.0.0.1',  # 数据库主机
        'PORT': 3306,  # 数据库端口
        'USER': 'remote',  # 数据库用户名
        'PASSWORD': '9A55w0_d',  # 数据库用户密码
        'NAME': 'hotmall',  # 数据库名字
    }
}

CACHES = {
    "default": {  # 默认
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "session": {  # session
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "verify_code": {  # 保存验证码
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",  # 选择redis2号库
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "history": {  # 用户浏览记录
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "carts": {  # 购物车
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/4",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },

}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# 配置工程日志
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 是否禁用已经存在的日志器
    'formatters': {  # 日志信息显示的格式
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    'filters': {  # 对日志进行过滤
        'require_debug_true': {  # django在debug模式下才输出日志
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {  # 日志处理方法
        'console': {  # 向终端中输出日志
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {  # 向文件中输出日志
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(os.path.dirname(BASE_DIR), 'logs/fatcat.log'),  # 日志文件的位置
            'maxBytes': 300 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose'
        },
    },
    'loggers': {  # 日志器
        'django': {  # 定义了一个名为django的日志器
            'handlers': ['console', 'file'],  # 可以同时向终端与文件中输出日志
            'propagate': True,  # 是否继续传递日志信息
            'level': 'INFO',  # 日志器接收的最低日志级别
        },
    }
}


# 配置静态文件加载路径
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]




# 指定本项目用户模型类
AUTH_USER_MODEL = 'users.User'

# 指定自定义用户认证后端
AUTHENTICATION_BACKENDS = ['users.utils.UsernameModelBackend']

# 判断用户是否登录后，指定未登录用户重定向地址
LOGIN_URL = '/login/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 指定邮件后端
EMAIL_HOST = 'smtp.163.com'  # 发邮件主机
#EMAIL_PORT = 465  # SSL加密端口
EMAIL_PORT = 25  # SSL加密端口
# EMAIL_USE_SSL = True  # 开启SSL
# EMAIL_USE_TLS = False
EMAIL_HOST_USER = '17717698342@163.com'  # 授权的邮箱
EMAIL_HOST_PASSWORD = 'UVvTePwB6QT56dbp'  # 邮箱授权时获得的密码，非注册登录密码
EMAIL_FROM = '肥猫商城<17717698342@163.com>'  # 发件人抬头
EMAIL_VERIFY_URL = 'http://127.0.0.1:8000/emails/verification/'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 指定邮件后端
# EMAIL_HOST = 'mail.qq.com'  # 发邮件主机
# EMAIL_PORT = 465  # SSL加密端口
# #EMAIL_USE_SSL = True  # 开启SSL
# #EMAIL_USE_TLS = False
# EMAIL_HOST_USER = 'kangdakefu@qq.com'  # 授权的邮箱
# EMAIL_HOST_PASSWORD = 'ghugupfyqubqcbeb'  # 邮箱授权时获得的密码，非注册登录密码
# EMAIL_FROM = '肥猫商城<kangdakefu@qq.com>'  # 发件人抬头
# EMAIL_VERIFY_URL = 'http://127.0.0.1:8000/emails/verification/'

#EMAIL_PORT = 25  # 发邮件端口
#163.com
#VZv5PVy9iBnj3XVm
#UVvTePwB6QT56dbp
#126.com
#KCvdd33hdY2he2aG
HAYSTACK_CONNECTIONS = {
    'default': {
        # 使用whoosh引擎
        'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshCNEngine',
        # 索引文件路径
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    }
}
# 当添加、修改、删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 5

# ALIPAY_APPID = '2016101400683639'
ALIPAY_APPID = '2016101200667363'
ALIPAY_DEBUG = True
ALIPAY_URL = 'https://openapi.alipaydev.com/gateway.do'
ALIPAY_RETURN_URL = 'http://127.0.0.1:8000/payment/status/'

# 微信支付（APIv3 Native）；演示模式为 True 时收银台为「模拟支付」，不走微信服务器
WECHAT_PAY_USE_DEMO = True
WECHAT_PAY_MCHID = ''
WECHAT_PAY_APPID = ''
WECHAT_PAY_API_V3_KEY = ''
WECHAT_PAY_SERIAL_NO = ''
WECHAT_PAY_PRIVATE_KEY_PATH = ''
WECHAT_PAY_NOTIFY_URL = 'http://127.0.0.1:8000/payment/wechat/notify/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 媒体文件配置（用户上传的图片存储路径）
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')  # 本地存储根目录
MEDIA_URL = '/media/'  # 浏览器访问图片的URL前缀

