# Generated by Django 3.2.25 on 2026-07-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0009_auto_20260727_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('level', models.IntegerField(unique=True, verbose_name='等级序号')),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='中奖概率(%)')),
                ('color', models.CharField(default='#FF6B6B', max_length=20, verbose_name='转盘颜色')),
            ],
            options={
                'verbose_name': '中奖等级',
                'verbose_name_plural': '中奖等级',
                'db_table': 'tb_prize_level',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='奖品数量')),
                ('prize_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.prizelevel', verbose_name='中奖等级')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.sku', verbose_name='商品')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
                'db_table': 'tb_prize',
            },
        ),
    ]
