# Generated by Django 3.2.25 on 2026-07-30 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_won', models.BooleanField(default=False, verbose_name='是否中奖')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.prize', verbose_name='奖品')),
                ('prize_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.prizelevel', verbose_name='中奖等级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '中奖记录',
                'verbose_name_plural': '中奖记录',
                'db_table': 'tb_lottery_record',
                'ordering': ['-create_time'],
            },
        ),
    ]
