# Generated by Django 3.2.25 on 2026-07-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_lotteryrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizelevel',
            options={'ordering': ['level'], 'verbose_name': '奖项', 'verbose_name_plural': '奖项'},
        ),
    ]
